export enum ActionTypes {
  FETCH_STATION_START = "FETCH_STATION_START",
  FETCH_STATION_SUCCESS = "FETCH_STATION_SUCCESS",
  FETCH_STATION_FAILURE = "FETCH_STATION_FAILURE",
  SELECT_STATION = "SELECT_STATION",
}
