export enum ActionTypes {
  FETCH_STATIONS_START = "FETCH_STATIONS_START",
  FETCH_STATIONS_SUCCESS = "FETCH_STATIONS_SUCCESS",
  FETCH_STATIONS_FAILURE = "FETCH_STATIONS_FAILURE",
  SELECT_STATION = "SELECT_STATION",
}
